aws_access_key_id: dGVzdAo=
aws_access_key_secret: dGVzdAo=
aws_region: dGVzdAo=
imagePullSecret: dGVzdAo=
modules_service:
  bucket_name: dGVzdAo=
ingress:
  host: terrarium.com
tls:
  crt: dGVzdAo=
  key: dGVzdAo=
