apiVersion: v1
kind: Secret
metadata:
    name: {{ include "terrarium.fullname" . }}
    namespace: {{ include "terrarium.fullname" . }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_access_key_secret }}
  AWS_DEFAULT_REGION: {{ .Values.aws_region }}
  WEBHOOK: {{ .Values.webhook }}
