apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terrarium.fullname" . }}-web-ui
  namespace: {{ include "terrarium.fullname" . }}
  labels:
    {{- include "terrarium.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web_service.replicas }}
  selector:
    matchLabels:
      {{- include "terrarium.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrarium.webSelectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "terrarium.fullname" . }}-regcred
      serviceAccountName: "default"
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.web_service.image.repository }}:{{ .Values.web_service.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.web_service.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http