apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terrarium.fullname" . }}-gateway
  namespace: {{ include "terrarium.fullname" . }}
  labels:
    {{- include "terrarium.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      {{- include "terrarium.gatewaySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrarium.gatewaySelectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "terrarium.fullname" . }}-regcred
      serviceAccountName: "default"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          args: 
            - "gateway"
            - "--registrar"
            - "$(REGISTRAR_ENDPOINT)"
            - "--dependency-manager"
            - "$(DEPENDENCY_MANAGER_ENDPOINT)"
            - "--version-manager"
            - "$(VERSION_MANAGER_ENDPOINT)"
            - "--release"
            - "$(RELEASE_ENDPOINT)"
            - "--storage"
            - "$(STORAGE_ENDPOINT)"
            - "--provider-version-manager"
            - "$(PROVIDER_VERSION_MANAGER_ENDPOINT)"
            - "--provider-storage"
            - "$(PROVIDER_STORAGE_ENDPOINT)"
            - "--aws-access-key-id"
            - "$(AWS_ACCESS_KEY_ID)"
            - "--aws-secret-access-key"
            - "$(AWS_SECRET_ACCESS_KEY)"
            - "--aws-region"
            - "$(AWS_DEFAULT_REGION)"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "terrarium.fullname" . }}
                  key: AWS_ACCESS_KEY_ID
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "terrarium.fullname" . }}
                  key: AWS_SECRET_ACCESS_KEY
                  optional: false
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "terrarium.fullname" . }}
                  key: AWS_DEFAULT_REGION
                  optional: false
            - name: REGISTRAR_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: REGISTRAR_ENDPOINT
            - name: VERSION_MANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: VERSION_MANAGER_ENDPOINT
            - name: DEPENDENCY_MANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: DEPENDENCY_MANAGER_ENDPOINT
            - name: TAG_MANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: TAG_MANAGER_ENDPOINT
            - name: RELEASE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: RELEASE_ENDPOINT
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: STORAGE_ENDPOINT
            - name: PROVIDER_VERSION_MANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: PROVIDER_VERSION_MANAGER_ENDPOINT
            - name: PROVIDER_STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: PROVIDER_STORAGE_ENDPOINT
            {{ include "terrarium.otelEndpoint" . | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 3001
