apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terrarium.fullname" . }}-browse
  namespace: {{ include "terrarium.fullname" . }}
  labels:
    {{- include "terrarium.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.browse_service.replicas }}
  selector:
    matchLabels:
      {{- include "terrarium.browseSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrarium.browseSelectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "terrarium.fullname" . }}-regcred
      serviceAccountName: "default"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.browse_service.image.repository }}:{{ .Values.browse_service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.browse_service.image.pullPolicy }}
          args:
            - "browse"
            - "--endpoint"
            - "0.0.0.0:3000"
            - "--registrar"
            - "$(REGISTRAR_ENDPOINT)"
            - "--version-manager"
            - "$(VERSION_MANAGER_ENDPOINT)"
            - "--aws-access-key-id"
            - "not-used"
            - "--aws-region"
            - "not-used"
            - "--aws-secret-access-key"
            - "not-used"
          env:
            - name: REGISTRAR_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: REGISTRAR_ENDPOINT
            - name: VERSION_MANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: VERSION_MANAGER_ENDPOINT
            {{ include "terrarium.otelEndpoint" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http