apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terrarium.fullname" . }}-gateway
  namespace: {{ include "terrarium.fullname" . }}
  labels:
    {{- include "terrarium.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      {{- include "terrarium.gatewaySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrarium.gatewaySelectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "terrarium.fullname" . }}-regcred
      serviceAccountName: "default"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          args: 
            - "gateway"
            - "--creation-service"
            - "$(CREATION_ENDPOINT)"
            - "--dependency-service"
            - "$(DEPENDENCY_ENDPOINT)"
            - "--session-service"
            - "$(SESSION_ENDPOINT)"
            - "--storage-service"
            - "$(STORAGE_ENDPOINT)"
            - "--aws-access-key"
            - "$(AWS_ACCESS_KEY_ID)"
            - "--aws-secret-key"
            - "$(AWS_SECRET_ACCESS_KEY)"
            - "--aws-region"
            - "$(AWS_DEFAULT_REGION)"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "terrarium.fullname" . }}
                  key: AWS_ACCESS_KEY_ID
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "terrarium.fullname" . }}
                  key: AWS_SECRET_ACCESS_KEY
                  optional: false
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "terrarium.fullname" . }}
                  key: AWS_DEFAULT_REGION
                  optional: false
            - name: CREATION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: CREATION_ENDPOINT
            - name: SESSION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: SESSION_ENDPOINT
            - name: DEPENDENCY_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: DEPENDENCY_ENDPOINT
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "terrarium.fullname" . }}-gateway-cm
                  key: STORAGE_ENDPOINT
          ports:
            - name: grpc
              containerPort: 3001
