apiVersion: v1
kind: Secret
metadata:
    name: {{ include "terrarium.fullname" . }}-ingress
    namespace: {{ include "terrarium.fullname" . }}
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
type: kubernetes.io/tls
