apiVersion: v1
kind: Service
metadata:
  name: nginx-static-server
  namespace: {{ include "terrarium.fullname" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "terrarium.nginxStaticServerSelectorLabels" . | nindent 8 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
