apiVersion: v1
kind: Service
metadata:
  name: {{ include "terrarium.fullname" . }}-provider-storage
  namespace: {{ include "terrarium.fullname" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "terrarium.providerStorageSelectorLabels" . | nindent 8 }}
  ports:
    - name: grpc
      port: 8080
      targetPort: 3001
      protocol: TCP
