name: Test Chart

on:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
        
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        
      - name: List changed
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Lint
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Set up kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Test install
        run: ct install
